Rearranged typeof check to handle null parameter (#2494)
* Rearranged typeof check to handle null parameter

Error:
Cannot read property 'toString' of null
  typeError: Cannot read property 'toString' of null
      at G:\CodeceptJS-Test\node_modules\codeceptjs\lib\step.js:115:22

Solution: Rearranged typeof check to handle crash when helper method is called with null parameter.

* Update step.js

* Update step.js